# Dream Tournament

###
# @name WelcomeRequest
GET http://localhost:8080

###
# group: User Progress
# @name CreateUserRequest
POST http://localhost:8080/api/user
Accept: application/json
Content-Type: application/json

{
  "username": "Yigit Cevik"
}

###
# group: User Progress
# @name UpdateLevelRequest
PUT http://localhost:8080/api/user/level
Content-Type: application/json

{
  "userId": 1
}

###
# group: World Cup Tournament
# @name EnterTournamentRequest
POST http://localhost:8080/api/tournament/enter
Content-Type: application/json

{
  "userId": 1
}

###
# group: World Cup Tournament
# @name ClaimRewardRequest
PUT http://localhost:8080/api/tournament/claim-reward
Content-Type: application/json

{
  "userId": 1
}

###
# group: World Cup Tournament
# @name GetGroupRankRequest
GET http://localhost:8080/api/tournament/group-rank
Content-Type: application/json

{
  "userId": 1,
  "tournamentId": 2
}

###
# group: World Cup Tournament
# @name GetGroupLeaderboardRequest
GET http://localhost:8080/api/tournament/group-leaderboard
Content-Type: application/json

{
  "groupId": 2
}

###
# group: World Cup Tournament
# @name GetCountryLeaderboardRequest
GET http://localhost:8080/api/tournament
Content-Type: application/json

{
  "tournamentId": 2
}
