# Dream Tournament

###
# group: User Progress
# @name CreateUserRequest 200
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "Yigit Cevik"
}

###
# group: User Progress
# @name CreateUserRequest 500 Invalid User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "Player1"
}

###
# group: User Progress
# @name UpdateLevelRequest 200
PUT http://localhost:8080/api/user/level
Content-Type: application/json

{
  "userId": 1
}

###
# group: User Progress
# @name UpdateLevelRequest 500 Invalid User
PUT http://localhost:8080/api/user/level
Content-Type: application/json

{
  "userId": 0
}

###
# group: World Cup Tournament
# @name EnterTournamentRequest 200
POST http://localhost:8080/api/tournament/enter
Content-Type: application/json

{
  "userId": 1
}

###
# group: World Cup Tournament
# @name EnterTournamentRequest 500 Invalid User
POST http://localhost:8080/api/tournament/enter
Content-Type: application/json

{
  "userId": 0
}

###
# group: World Cup Tournament
# @name EnterTournamentRequest 500 Invalid Level
POST http://localhost:8080/api/tournament/enter
Content-Type: application/json

{
  "userId": 9
}

###
# group: World Cup Tournament
# @name EnterTournamentRequest 500 Invalid Coin
POST http://localhost:8080/api/tournament/enter
Content-Type: application/json

{
  "userId": 10
}

###
# group: World Cup Tournament
# @name ClaimRewardRequest 200
PUT http://localhost:8080/api/tournament/claim-reward
Content-Type: application/json

{
  "userId": 1
}

###
# group: World Cup Tournament
# @name ClaimRewardRequest 500 Invalid User
PUT http://localhost:8080/api/tournament/claim-reward
Content-Type: application/json

{
  "userId": 0
}

###
# group: World Cup Tournament
# @name GetGroupRankRequest 200
GET http://localhost:8080/api/tournament/group-rank?
    userId=1&
    tournamentId=2

###
# group: World Cup Tournament
# @name GetGroupRankRequest 500 Invalid Tournament
GET http://localhost:8080/api/tournament/group-rank?
    userId=1&
    tournamentId=0

###
# group: World Cup Tournament
# @name GetGroupLeaderboardRequest 200
GET http://localhost:8080/api/tournament/group-leaderboard?
    groupId=2

###
# group: World Cup Tournament
# @name GetCountryLeaderboardRequest 200
GET http://localhost:8080/api/tournament/country-leaderboard?
    tournamentId=2

###
# @name WelcomeRequest
GET http://localhost:8080